
-- DDL(데이터 정의어)
-- CREATE TABLE
CREATE TABLE BOARD (
    BNO NUMBER(10), /*NOT NULL UNIQUE,*/ -- 글번호는 비어있으면 안되고 유니크해야한다.
    TITLE VARCHAR2(200) NOT NULL, /*글제목200글자 제한*/
    CONTENT VARCHAR2(3000), /*NOT NULL 을 안쓰면 자동으로 NULL 이 생성*/ 
    WRITER VARCHAR2(50) NOT NULL,
    REG_DATE DATE NOT NULL --날짜는 필수값으로 
);

-- PK 설정
ALTER TABLE BOARD ADD CONSTRAINT pk_board_bno PRIMARY KEY (BNO);
 /*제약조건을 추가합니다 */
--bno 에게 제약조건 PK를 건다.

-- CREATE TABLE
CREATE TABLE REPLY (
    REPLY_NO NUMBER(10),
    REPLY_CONTENT VARCHAR2(500) NOT NULL,
    REPLY_WRITE VARCHAR(50) NOT NULL,
    BNO NUMBER(10)
);

-- PK 설정
ALTER TABLE REPLY ADD CONSTRAINT pk_reply_reply PRIMARY KEY (REPLY_NO); 

-- FK 설정
ALTER TABLE REPLY ADD CONSTRAINT fk_reply_bno FOREIGN KEY (BNO) REFERENCES BOARD (BNO); /*--모든 테이블에 있는 BNO를 FK로 설정 */

--컬럼 변경
/*오라클은 ADD 컬럼이 아니라 그냥 ADD*/
ALTER TABLE REPLY ADD (REPLY_REG_DATE DATE NOT NULL);
ALTER TABLE REPLY DROP COLUMN REPLY_REG_DATE;

SELECT * FROM REPLY;
